@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(User, "Пользователь", "Пользователь трекера задач")
Container(Frontend, "Фронтенд", "Фронтенд")
Container(MainService, "Главный сервис", "Главный сервис, который отвечает за клиентское API и за регистрацию и аутентификацию пользователей")
Container(StatisticsService, "Сервер статистик", "Сервер по сбору статистик")
Container(TaskService, "Сервер задач и комментариев", "Сервер для процессинга задач и комментариев")
Container(Broker, "Broker-Kafka", "Лог-брокер для процессинга комментариев и задач в статистике")
ContainerDb(Log, " ClickHouse", "БД для хранения пользователей")
ContainerDb(LogStats, "ClickHouse", "БД для логгирования статистикс")
ContainerDb(LogTask, "ClickHouse", "БД для хранения задач")

Rel(User, Frontend, "Пользуется")
Rel(Frontend, MainService, "REST API")
Rel(MainService, StatisticsService, "gRPC")
Rel(MainService, TaskService, "gRPC")
Rel(TaskService, Broker, "gRPC")
Rel(Broker, StatisticsService, "gRPC")

Rel(MainService, Log, "SQL")
Rel(StatisticsService, LogStats, "SQL")
Rel(TaskService, LogTask, "SQL")


@enduml
